extend type Education {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Education", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Education`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Education.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Experience {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Experience", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Experience`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Experience.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Project {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Project", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Project`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Project.user", purpose: IMPLICIT_REF_FIELD)
}
extend type ProjectAsset {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ProjectAsset", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ProjectAsset`.`project`. It must match the value of `Project`.`id`. See `@ref` for how to customize it.
  """
  projectId: UUID! @fdc_generated(from: "ProjectAsset.project", purpose: IMPLICIT_REF_FIELD)
}
extend type Skill {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Skill", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Skill`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Skill.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
