extend type Query {
  """
  ✨ Look up a single `Education` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  education(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Education_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Education_FirstRow
  ): Education @fdc_generated(from: "Education", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Experience` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  experience(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Experience_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Experience_FirstRow
  ): Experience @fdc_generated(from: "Experience", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Project` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  project(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project @fdc_generated(from: "Project", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProjectAsset` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  projectAsset(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectAsset_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectAsset_FirstRow
  ): ProjectAsset @fdc_generated(from: "ProjectAsset", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Skill` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  skill(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Skill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Skill_FirstRow
  ): Skill @fdc_generated(from: "Skill", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Education` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  educations(
    """
    Filter condition to narrow down the query results.
    """
    where: Education_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Education_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Education_Having
  ): [Education!]! @fdc_generated(from: "Education", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Experience` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  experiences(
    """
    Filter condition to narrow down the query results.
    """
    where: Experience_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Experience_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Experience_Having
  ): [Experience!]! @fdc_generated(from: "Experience", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Project` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projects(
    """
    Filter condition to narrow down the query results.
    """
    where: Project_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Project_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Project_Having
  ): [Project!]! @fdc_generated(from: "Project", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProjectAsset` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projectAssets(
    """
    Filter condition to narrow down the query results.
    """
    where: ProjectAsset_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProjectAsset_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProjectAsset_Having
  ): [ProjectAsset!]! @fdc_generated(from: "ProjectAsset", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Skill` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  skills(
    """
    Filter condition to narrow down the query results.
    """
    where: Skill_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Skill_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Skill_Having
  ): [Skill!]! @fdc_generated(from: "Skill", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
